### ISSUE TITLE
macos

### ISSUE THREAD

**Issue by jrc2139** [johalun/DD2440#1]
https://github.com/johalun/DD2440/blob/240671975ad5f32fe9cbf78901ccd2c649dc8440/uniform-vs-no-majority/main.c#L107

build fails on macOS 10.12.6 unless changed to CLOCK_MONOTONIC_RAW

easy fix! thanks for doing this!

**Comment by johalun** [comment]
Thanks!  CLOCK_MONOTONIC_PRECISE seem to be FreeBSD specific. Should build fine on Mac and Linux now.
